//上海市地图对照表
export default 
{
    HuangPu: "黄浦区",
    XuHui: "徐汇区",
    ChangNing: "长宁区",
    JingAn: "静安区",
    PuTuo: "普陀区",
    HongKou: "虹口区",
    YangPu: "杨浦区",
    PuDong: "浦东新区",
    MinHang: "闵行区",
    BaoShan: "宝山区",
    JiaDing: "嘉定区",
    JingShan: "金山区",
    SongJiang: "松江区",
    QingPu: "青浦区",
    FengXian: "奉贤区",
    ChongMing: "崇明区",
}
// [
//     { name: "黄浦区", code: "HuangPu"},
//     { name: "徐汇区", code: "XuHui"},
//     { name: "长宁区", code: "ChangNing"},
//     { name: "静安区", code: "JingAn"},
//     { name: "普陀区", code: "PuTuo"},
//     { name: "虹口区", code: "HongKou"},
//     { name: "杨浦区", code: "YangPu"},
//     { name: "浦东新区", code: "PuDong"},
//     { name: "闵行区", code: "MinHang"},
//     { name: "宝山区", code: "BaoShan"},
//     { name: "嘉定区", code: "JiaDing"},
//     { name: "金山区", code: "JingShan"},
//     { name: "松江区", code: "SongJiang"},
//     { name: "青浦区", code: "QingPu"},
//     { name: "奉贤区", code: "FengXian"},
//     { name: "崇明区", code: "ChongMing"},
// ]